const { ethers, network } = require('hardhat');
const { getForNetwork } = require('./addresses');

async function main() {
  const { endemicErc721Factory } = getForNetwork(network.name);

  const verifiedUsers = [
    {
      id: '0x1f81b0bb1ec7b7dbb8241a6693f72835b081f8cc',
      role: 'ARTIST',
      email: 'borcic.peuc@gmail.com',
      displayName: 'natalia',
      fullName: 'Natalia Borčić Peuc',
      imageUrl: null,
      description: '',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@natalia',
    },
    {
      id: '0x9f81287b7195a49fcb8155c2edd7f47b5e5f01e1',
      role: 'ARTIST',
      email: null,
      displayName: 'unnamed225',
      fullName: 'unnamed',
      imageUrl: null,
      description: null,
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@unnamed225',
    },
    {
      id: '0x5de2e24609c53482998ee09750bc33a1993eec0c',
      role: 'ARTIST',
      email: null,
      displayName: 'unnamed223',
      fullName: 'unnamed',
      imageUrl: null,
      description: null,
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@unnamed223',
    },
    {
      id: '0x71b8c474d8b9bf5fa5f12976e1f639e00ae5c9f8',
      role: 'ARTIST',
      email: 'Ljiljana.markovic24@gmail.com',
      displayName: 'lili_24',
      fullName: 'Ljiljana Marković',
      imageUrl: null,
      description: 'Illustrator based in Croatia\n',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@lili_24',
    },
    {
      id: '0x598c13d146927591b7558dcf958ea51fc20844d0',
      role: 'ARTIST',
      email: null,
      displayName: null,
      fullName: null,
      imageUrl: null,
      description: null,
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '0x598c13d146927591b7558dcf958ea51fc20844d0',
    },
    {
      id: '0x65526e45ae6faef1c1cd5fc33a8e8408df4e2f29',
      role: 'ARTIST',
      email: null,
      displayName: null,
      fullName: null,
      imageUrl: null,
      description: null,
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '0x65526e45ae6faef1c1cd5fc33a8e8408df4e2f29',
    },
    {
      id: '0x3ee1eebdb9d7f1ac3b8d5fb7cc39fbb724db36c0',
      role: 'ARTIST',
      email: null,
      displayName: 'milisa_travka',
      fullName: 'Milisa_Travka',
      imageUrl:
        'https://storage.googleapis.com/endemic/profile/1692724125448-Ds8y6mzi_ow.jpg',
      description: '',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl:
        'https://storage.googleapis.com/endemic/profile/1692724126132-g3Jl9cOrWyU.jpg',
      slug: '@milisa_travka',
    },
    {
      id: '0x2f0a1210fe8eace6e26b30df0675c12258af75b8',
      role: 'ARTIST',
      email: '225forev@gmail.com',
      displayName: '8888k',
      fullName: 'Kuandyk Toleubay',
      imageUrl:
        'https://storage.googleapis.com/endemic/profile/1687096653393-WhatsApp_Image_2022-03-01_at_22_31_34__2_.jpeg',
      description: 'Digital marketer',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl:
        'https://storage.googleapis.com/endemic/profile/1687096654044-pexels-piccinng-3075993.jpg',
      slug: '@8888k',
    },
    {
      id: '0x1301d1dbf55728efea66fc4fc1aa582e42416747',
      role: 'ARTIST',
      email: 'thabazin@gmail.com',
      displayName: 'typoplust',
      fullName: 'Typoplust',
      imageUrl:
        'https://storage.googleapis.com/endemic/profile/1691492237300-profilna.jpeg',
      description:
        'Typoplust was created primarily for therapeutic purposes. Putting chaos into order. In the head, and on "paper". This can also be seen from the works, which are minimalist. At the same time, both simple and complicated. In ten years, about forty fonts (in vector form) plus about fifty posters were created. The fonts are mostly geometric , placed on the default network and according to the default rules. Posters follow font rules.Minimize2maximize. And Cats!',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl:
        'https://storage.googleapis.com/endemic/profile/1691492237838-banner-typolust.jpeg',
      slug: '@typoplust',
    },
    {
      id: '0x2d6c5cd53d17273d49e473c20ab26ab732233943',
      role: 'ARTIST',
      email: null,
      displayName: 'unnamed224',
      fullName: 'unnamed',
      imageUrl: null,
      description: null,
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@unnamed224',
    },
    {
      id: '0x243eb379f1c049fb6813158907aa6d27855ed6fc',
      role: 'ARTIST',
      email: 'kaca.svedruzic@gmail.com',
      displayName: 'kachacha',
      fullName: 'Kaca Svedruzic',
      imageUrl:
        'https://storage.googleapis.com/endemic/profile/1691252462226-16683921_10212156399608270_2252148189970756769_n.jpeg',
      description: '',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@kachacha',
    },
    {
      id: '0x7304e3fb83eaff8914325865621eefff7b486599',
      role: 'ARTIST',
      email: 'kalinin@gmail.com',
      displayName: 'ekalinina_art',
      fullName: 'Ekaterina Kalinina',
      imageUrl:
        'https://storage.googleapis.com/endemic/profile/1691512603290-IMG-0966.JPG',
      description:
        'I am a digital illustrator. I draw in different styles. Most of all I love watercolor and comic style',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl:
        'https://storage.googleapis.com/endemic/profile/1691512605217-coffe_milk.JPG',
      slug: '@ekalinina_art',
    },
    {
      id: '0x1d0069d7f2ad47313ffa38e7b232a9f1fe622355',
      role: 'ARTIST',
      email: 'max1996red2104devil0600fan@mail.ru',
      displayName: 'mkei',
      fullName: 'Max Kochergin ',
      imageUrl:
        'https://storage.googleapis.com/endemic/profile/1694013988376-IMG_0872.jpeg',
      description: '',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@mkei',
    },
    {
      id: '0x4fa40e0b18a1872061159bc841281963b4f88f8a',
      role: 'ARTIST',
      email: 'martina.miholic@gmail.com',
      displayName: 'martinamiholic',
      fullName: 'Martina Miholic',
      imageUrl:
        'https://storage.googleapis.com/endemic/profile/1690800838759-65b_copy.jpg',
      description: 'Multimedia artist',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl:
        'https://storage.googleapis.com/endemic/profile/1690800843532-65b_copy.jpg',
      slug: '@martinamiholic',
    },
    {
      id: '0x81ad0a3a723b05f0c2b1c47d64469b3a083cfedf',
      role: 'ARTIST',
      email: 'ateneaangelart@gmail.com',
      displayName: 'at_angel_art',
      fullName: 'Atenea Angel',
      imageUrl:
        'https://storage.googleapis.com/endemic/profile/1691211343433-IMG_2678.jpg',
      description:
        'Hello. Welcome to my virtual world, here you will find everything to buy. Graphic artist of 19 yo, come to see my creations and spend a lot.',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl:
        'https://storage.googleapis.com/endemic/profile/1690295769054-IMG_1108.jpg',
      slug: '@at_angel_art',
    },
    {
      id: '0xc78618f583607f44c533b52bb4208400d56a3643',
      role: 'ARTIST',
      email: null,
      displayName: 'lupino',
      fullName: 'Stefan Lupino',
      imageUrl: null,
      description: '',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@lupino',
    },
    {
      id: '0xce4ebe6283ed17575822aadc59ac2b83c7938b73',
      role: 'ARTIST',
      email: 'dkraskovic@yahoo.com',
      displayName: 'deniskraskovic',
      fullName: 'Denis Kraskovic',
      imageUrl:
        'https://storage.googleapis.com/endemic/profile/1691237064787-Portret_Denis_Kraskovic_21.jpg',
      description:
        'Denis Kraškovič was born in 1972 in Zagreb, where he finished the School of Applied Arts and Design. He graduated in sculpture from the Academy of Fine Arts in Zagreb in 1994, in the class of Professor Stanko Jančić. In 2012, he completed a master’s degree in sculpture at the Academy of Fine Arts in Ljubljana, under the mentorship of Professor Jože Barši. In 1997 he started teaching sculpture-related subjects at the School of Applied Arts and Design in Zagreb. In 2008, he first became an assistant professor and later an associate professor at the Department of Fine Arts of the Academy of Arts and Culture in Osijek. As part of his work as a teacher, he founded the Jarčevac International Student Fine Arts Workshop (wood sculpting), and led many other creative projects for students. In 2015 and 2016, he was a visiting professor at the Department of Sculpture of the Faculty of Music and Visual Arts in Pecs, Hungary. He is the recipient of many awards and recognitions for his work as both an artist and a teacher. He won, amongst others, the 2000 Grand Prix at the Youth Salon in Zagreb, the 2015 Grand Prix at the Zagorje Art Salon, the Special Jury Prize at the XI Triennial of Croatian Sculpture in 2012, and was awarded the second prize at The Residents video competition in Olomouc, the Czech Republic. His Journey to the End of the World of General Umberto Nobile’s Expedition was ranked by Q Strip magazine in 2015 amongst the top five Croatian comic books of all time. He has exhibited at numerous solo and group exhibitions in both Croatia and abroad – from Zagreb, Split, Rijeka, Osijek, Pula, Dubrovnik, to Berlin, Budapest, Turin, Prague, Krakow, Vienna, Los Angeles, Johannesburg, etc. He is the author of fascinating public sculptures, such as The Whale sculpture on Jarun Lake, The Walrus and The Lamb sculptures outside the Arena in Zagreb, and two monumental sculptures, Neanderthal I and II, in Krapina. His public wooden sculptures Goodness in Kostanjevica on the Krka River and A Monument to a Happy Childhood in Kočevje in Slovenia should also be singled out. He has been a member of the Croatian Freelance Artists’ Association since 2019 and has worked as a freelance artist ever since. \nWeb porotfolio: deniskraskovic.com',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@deniskraskovic',
    },
    {
      id: '0x97c5a457570b6c180cf8633b9ac55346270c7d90',
      role: 'ARTIST',
      email: null,
      displayName: 'alice',
      fullName: 'Alice',
      imageUrl: null,
      description: 'Artist',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@alice',
    },
    {
      id: '0x5ed384389fc706c1d8921e700c87a28a22dc7fe3',
      role: 'ARTIST',
      email: null,
      displayName: null,
      fullName: null,
      imageUrl: null,
      description: null,
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '0x5ed384389fc706c1d8921e700c87a28a22dc7fe3',
    },
    {
      id: '0x2eaaa26adcdf1de93dba22eb169c0165016e655d',
      role: 'ARTIST',
      email: null,
      displayName: 'unnamed098',
      fullName: 'unnamed',
      imageUrl: null,
      description: null,
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@unnamed098',
    },
    {
      id: '0x02e23a26eac598231027c8e4576d23b8159dbfda',
      role: 'ARTIST',
      email: null,
      displayName: 'unnamed382',
      fullName: 'unnamed',
      imageUrl: null,
      description: null,
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@unnamed382',
    },
    {
      id: '0xcdfa5fb2f0d50b075020f19b524864eb1cc20857',
      role: 'ARTIST',
      email: null,
      displayName: 'unnamed447',
      fullName: 'unnamed',
      imageUrl: null,
      description: null,
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@unnamed447',
    },
    {
      id: '0xf2124e8ce4a2f71c5d33ac70819a55e66fef6557',
      role: 'ARTIST',
      email: 'darijaburic74@gmail.com',
      displayName: 'lapuh',
      fullName: 'Željko Lapuh',
      imageUrl:
        'https://storage.googleapis.com/endemic/profile/1691265562275-lapuh.jpeg',
      description:
        'Željko Lapuh was born on May 27, 1951 in Split. He finished elementary school\nand high school in Zagreb, and in 1976 he graduated in painting at the Academy\nof Fine Arts in Zagreb, in the class of Professor Šime Perić. Since then, he has\nbeen a member of the Croatian Association of Artists (HDLU ) and works in the\nart life of Croatia as an independent artist.\nIn the period from 1976 to 1980, he was a collaborator in the Master\nWorkshop of Ljubo Ivančić and Nikola Reiser.\nIn 2004, he became a full professor at the Academy of Fine Arts in Zagreb.\n\nHe has exhibition at about forty solo and over two hundred group exhibitions\nat home and abroad. He has won many awards for painting, of which the Grand\nPrix of the Zagreb Salon 1993 stands out, and for special merits in Croatian\nculture, he was awarded the order of Danica Hrvatska with the image of Marko\nMarulić.\n\nThe works of Željko Lapuh can be found in galleries and museums, as well as in\nnumerous private collections in the country and abroad.',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@lapuh',
    },
    {
      id: '0x9cea9553575c272cc09274631f44d32b5d62c19e',
      role: 'ARTIST',
      email: null,
      displayName: 'unnamed728',
      fullName: 'unnamed',
      imageUrl: null,
      description: null,
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@unnamed728',
    },
    {
      id: '0xf511bc47ebe42427e550bd11cff61115b07b84c0',
      role: 'ARTIST',
      email: null,
      displayName: 'unnamed448',
      fullName: 'unnamed',
      imageUrl: null,
      description: null,
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@unnamed448',
    },
    {
      id: '0x5fd490d48c8d570b9a53a0054bf43b47f1df2085',
      role: 'ARTIST',
      email: null,
      displayName: 'unnamed449',
      fullName: 'unnamed',
      imageUrl: null,
      description: null,
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@unnamed449',
    },
    {
      id: '0xfff8b0cd2646cf2ffc90981982b900db6f7bd248',
      role: 'ARTIST',
      email: 'rita.vitinchuk@mail.ru',
      displayName: 'kataba',
      fullName: 'Vitinchuk Rita',
      imageUrl:
        'https://storage.googleapis.com/endemic/profile/1691683022396-g6ZvFqE-Jxg.jpg',
      description:
        "I've been drawing all my life, I love creating lively and interesting characters. In my work, the opportunity to develop and expand my knowledge is important for me.",
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl:
        'https://storage.googleapis.com/endemic/profile/1691683022996-qXzhaB-pl3U.jpg',
      slug: '@kataba',
    },
    {
      id: '0x12aae6180729cf0d472cc23471139819dbcf37c2',
      role: 'ARTIST',
      email: 'nikola.sinkovic@gmail.com',
      displayName: 'nikolasinkovic',
      fullName: 'Nikola Sinković',
      imageUrl: null,
      description:
        "Nikola Sinković was born in Zagreb on August 6, 1971. He attended elementary school in Donja Stubica and secondary school in Krapina, after which he enrolled in the Design Study at the Faculty of Architecture of the University of Zagreb. He graduated in 1997 and obtained the title of graduate designer. He worked as an art teacher at the Donja Stubica Primary School, and then at the Zabok School of Art, Design, Graphics and Clothing, where he still works as a teacher in the field of design.\nThe beginnings of Sinković's artistic activity are already visible in elementary school, where he developed with the support of his art teacher - acad. painter Darko Bubank and continue through high school education when he organizes his first solo exhibition. During his studies, his artistic expression, in different media, was influenced by professors Nenad Dogan in design, then Darko Bakliža and Josip Vaništa in drawing and Stanko Herceg in photography.\nIn addition to the above art disciplines, he deals with web design, interior design and industrial design, and illustration. He realized dozens of web projects, several residential and catering facilities and illustrated several books and textbooks. He designs numerous magazines, posters, exhibition catalogs and books with his recognizable minimalist visual handwriting.\nHe is a participant in many art colonies in Hrvatska Zagorje, he participated in two Zagorje salons in the Krapina City Gallery, and he organized, in addition to several group exhibitions, four solo exhibitions (Krapina, Zabok, Gornja Stubica).",
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@nikolasinkovic',
    },
    {
      id: '0x3052f7eb5eabb82c6c2b8b02ca653e905fad351e',
      role: 'ARTIST',
      email: 'duje.medic@gmail.com',
      displayName: 'dujemedic',
      fullName: 'Duje Medić',
      imageUrl:
        'https://storage.googleapis.com/endemic/profile/1691184876997-2.jpg',
      description:
        'Duje Medić (Brela, 1986) earned his Masters at the Zagreb Academy of Fine Arts, printmaking department in 2010. He has participated in many group and twenty one solo exhibitions. Hommage to a pencil (Studio of Modern Gallery Josip Račić, Zagreb 2015) with Josip Vaništa and Davor Vrankić is the exhibition that should be singled out. 2015 he participated at the international workshop Science meets Art in Brela, Croatia. The workshop was organized by prof. Ivan Đikić (Goethe Institute, Frankfurt), Dr.Martina Mijušković (Genomics England) and Duje Medić.\nIn 2016 he was a resident in Cite International des Arts, Paris, France. \nHe does pencil drawings, printmaking and graphic design. He is a member of HZSU (Croatian Freelance Artists Association). \n',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl:
        'https://storage.googleapis.com/endemic/profile/1691185223279-20190620_153229.jpg',
      slug: '@dujemedic',
    },
    {
      id: '0x94dc4d76fa819fa557aa7a2aa327655d2caf2be2',
      role: 'ARTIST',
      email: 'iabibch2001@gmail.com',
      displayName: 'yakov_inside',
      fullName: 'Yakov',
      imageUrl: null,
      description: 'iabibch2001@gmail.com',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@yakov_inside',
    },
    {
      id: '0xfd1ea1984abc6b50302322edc04d151cd259c634',
      role: 'ARTIST',
      email: 'ppurgar6@gmail.com',
      displayName: 'patricija_purgar',
      fullName: 'Patricija Purgar',
      imageUrl:
        'https://storage.googleapis.com/endemic/profile/1691266613466-profilna1.jpg',
      description:
        'Patricija Purgar was born 1990 in Zagreb.  She graduated from the Academy of Fine Arts in Zagreb in 2013 attaining a Master of Fine Arts (MFA) Degree in Painting. She participated in a number of collective exhibitions in Croatia, Slovenia and Germany and solo exhibitions in Croatia.\nShe is a HDLU (Croatian Association of Fine Artists) and HZSU (Croatian Freelance Artists Association) member. She lives and works in Zagreb, Croatia.\n',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@patricija_purgar',
    },
    {
      id: '0x159242205969c640b308d4fda8a7a1d67097f3da',
      role: 'ARTIST',
      email: 'dankofriscic70@yahoo.com',
      displayName: 'danko_friscic',
      fullName: 'Danko Friščić',
      imageUrl:
        'https://storage.googleapis.com/endemic/profile/1691432340143-profilna.jpeg',
      description:
        "Danko Friščić was born on May 30th 1970.,in the unfathomable part of the Galaxy of his own\nMind,not remembering from which planet,nor that he's an artist.His works produce him.\nPainter,multimedia artist(?),professor at Zagreb Academy of Fine Arts .\nHe is a member of Croatian Association of Artists (HDLU),and a winner of several international and\ndomestic awards for his works,which are a part of many private and public collections.\nHe exhibited at more than 200 solo and collective exhibitions in Croatia\n(Labin,Pula,Rovinj,Rijeka,Varaždin,Osijek,Split,Dubrovnik..etc) and abroad\n(Rome,Florence,Turin,Paris,Metz,Vienna,Praque,Amsterdam,Berlin,Collogne,Braunschweig,Gdansk,\nKrakow,Budapest,Skopje,Sofia,\nBratislava,Ljubljana,Istanbul,Ankara,Santiago de Chille,Iowa City (USA),Port Au-Prince in Haiti ,etc…)",
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@danko_friscic',
    },
    {
      id: '0xa2e83517170648df0b9a143d1e8682b06f17860b',
      role: 'ARTIST',
      email: null,
      displayName: null,
      fullName: null,
      imageUrl: null,
      description: null,
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '0xa2e83517170648df0b9a143d1e8682b06f17860b',
    },
    {
      id: '0xabcb7167070a91699216221f331b1096b5733638',
      role: 'ARTIST',
      email: null,
      displayName: 'unnamed423',
      fullName: 'unnamed',
      imageUrl: null,
      description: null,
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@unnamed423',
    },
    {
      id: '0x6ea782a778fa450a3e7881f2bfb74ea3ce359967',
      role: 'ARTIST',
      email: null,
      displayName: 'danijel_zezelj',
      fullName: 'Danijel Žeželj',
      imageUrl:
        'https://storage.googleapis.com/endemic/profile/danijel_zezelj.jpeg',
      description:
        "Danijel Žeželj is a graphic novelist, animator, painter and illustrator. His comics and illustrations has been published in Europe, Asia, Africa, Australia and North, Middle and South America. His work has been published by DC Comics, Marvel Comics, Dark Horse, Heavy Metal, The New York Times, Harper's Magazine, Dargaud, Glénat, Eris Edizioni, etc. He is author of twenty five graphic novels and seven short animation movies. He created a series of multimedia performances merging live painting with live music. They premiered in the USA and Europe. In Zagreb, Croatia, he co-founded a workshop and publishing house Petikat.",
      isVerified: true,
      isFeatured: true,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@danijel_zezelj',
    },
    {
      id: '0x5990aade3a03451bed04dd53b91309cd2ecc3b48',
      role: 'ARTIST',
      email: 'jarodpguest@proton.me',
      displayName: 'ergotjudas',
      fullName: 'Ergot Judas',
      imageUrl:
        'https://storage.googleapis.com/endemic/profile/1690581267948-happyghengis_an_orchestra_of_costumed_freaks_and_misfits_playin_4268b570-f260-4c6e-a9d6-6298ab72253b.png',
      description:
        'Australian based multidisciplinary artist creating digital work for your viewing pleasure.',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl:
        'https://storage.googleapis.com/endemic/profile/1690581272981-happyghengis_haunting_eerie_an_orchestra_of_adults_in_halloween_0576901b-df94-40e6-a86c-219bf9ed22c0.png',
      slug: '@ergotjudas',
    },
    {
      id: '0xa6563ec05719eac18abe1306a1f86079f6f31c7b',
      role: 'ARTIST',
      email: 'mirkomilicic0901@gmail.com',
      displayName: 'mm',
      fullName: 'Mirko Miličić',
      imageUrl:
        'https://storage.googleapis.com/endemic/profile/1691178627947-download.jpg',
      description:
        'Mirko Miličić, born 9th January 1985 in Zagreb, Croatia. He graduated from the School of Applied Art and Design, and a Master of Design at the Faculty of Architecture. With an approach to design characterized by a clear inquisitiveness for products, industry and processes, Mirko Miličić  works on various projects ranging from product, interior and furniture  design to illustration and motion graphics . The provided services are characterized by simple and relevant design approach which endeavors in always offering innovative and strong solutions based on methodical process. Up to now he worked in product design, interior design, furniture design, web design, illustrations, graphics and graphic animations. He had a different exhibition in the field of furniture design, painting and illustration. He began painting from the time of primary schools in the study, "Tanay", after the completion of the School of Applied Art and Design he has upgraded its talent with the academic artist Maja Mubrin. He lives and works in Zagreb.',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@mm',
    },
    {
      id: '0x575a5795cdae10721061036cb19b96e794b65ec8',
      role: 'ARTIST',
      email: null,
      displayName: 'unnamed895',
      fullName: 'unnamed',
      imageUrl: null,
      description: null,
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@unnamed895',
    },
    {
      id: '0x87980001292939889898ad6d200d89c66fd8471d',
      role: 'ARTIST',
      email: 'masnankinaksenia1@gmail.com',
      displayName: 'ksenus',
      fullName: 'Ksenus',
      imageUrl:
        'https://storage.googleapis.com/endemic/profile/1691605991297-Picsart_23-08-09_21-12-25-033.jpg',
      description:
        "I am Ksenia. Creating art on my mobile phone is my passion. I am able to convey beauty and emotions through the limited screen, utilizing my academic knowledge of painting. Every tiny detail is brought to life in my original artworks, aiming to give viewers an unforgettable experience. My phone becomes a tool through which I express my individuality and inspiration. I create art pieces that inspire awe and leave a lasting impression on people's hearts. My artificial masterpieces reflect my passion and skill, proving that art knows no boundaries and can be created in any circumstances. I am an artist, skillfully harnessing the power of my phone to transform it into a magical window to the world of beauty.",
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl:
        'https://storage.googleapis.com/endemic/profile/1691605737422-Picsart_23-08-09_21-28-22-524.jpg',
      slug: '@ksenus',
    },
    {
      id: '0x36564f5fd15f23217340be510b9ba100ed29a072',
      role: 'ARTIST',
      email: null,
      displayName: 'emcn',
      fullName: 'Edward Neumann',
      imageUrl:
        'https://storage.googleapis.com/endemic/profile/1645458255884-The_Abyss.jpg',
      description:
        'Self taught photographer and digital artist. My name is Edward Neumann, I have a BA/BSc (Joint Honours) in English Literature and Philosophy from The University of Manchester, UK. Having spent most of my life in a city like London it’s hard not to notice the architecture that surrounds you on a daily basis. As I have grown up, so has the architectural landscape around me. It is that which captures my imagination most. My entire body of work has been shot exclusively in London over a period spanning 10 years.\n\nReoccurring themes:\nSYMMETRY, PERSPECTIVE, MOTIFS, LEADING LINES, SERENDIPITY AND HARMONY.',
      isVerified: true,
      isFeatured: true,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl:
        'https://storage.googleapis.com/endemic/profile/1645023382901-Vel_2__Pano_copy.jpg',
      slug: '@emcn',
    },
    {
      id: '0x92dd8281daa72d0f9b7dd212bdbf9ab6465b0522',
      role: 'ARTIST',
      email: null,
      displayName: 'unnamed444',
      fullName: 'unnamed',
      imageUrl: null,
      description: null,
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@unnamed444',
    },
    {
      id: '0xf18e7298c1c07758746acf98b60b674384196636',
      role: 'ARTIST',
      email: null,
      displayName: 'pankrateva_v',
      fullName: 'Pankrateva Viktoria',
      imageUrl:
        'https://storage.googleapis.com/endemic/profile/1693591884383-6E8E686A-FE70-439A-9490-885DB95CD549.jpeg',
      description: '',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl:
        'https://storage.googleapis.com/endemic/profile/1693591887976-9DF23AEE-0890-4123-B102-B217D980993D.jpeg',
      slug: '@pankrateva_v',
    },
    {
      id: '0x716fcba67369797b9e2d653506767cddd2dc74cc',
      role: 'ARTIST',
      email: null,
      displayName: 'paolo_gentilini',
      fullName: 'Paolo Gentilini',
      imageUrl:
        'https://storage.googleapis.com/endemic/profile/1644582044047-Paolo_Gentilini_-_Paolo_Gentilini.jpeg',
      description:
        'Paolo Gentilini, born in Croatia on the 9th of January 1990 is an Italo-Croatian visual artist and filmmaker. He attended various international filmmaking, VFX and 3D schools such as: Prague Film School, Algebra University Zagreb, New York Film Academy and Escapes Studios London. He is currently living and working in Croatia as CEO of his own production company “Gentilini Film” producing music videos for Croatian and international artists as well as regional and national commercials. Additionally, he develops his own projects in his personal style.',
      isVerified: true,
      isFeatured: true,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@paolo_gentilini',
    },
    {
      id: '0x4ee5655d7d10fd00a74e41b9a11e77b45cfd83a3',
      role: 'ARTIST',
      email: null,
      displayName: 'endy',
      fullName: 'Endy',
      imageUrl: null,
      description: '',
      isVerified: true,
      isFeatured: true,
      isSuperstar: true,
      isCollector: true,
      headerImageUrl: '',
      slug: '@endy',
    },
    {
      id: '0xe3b1a2cb1b4ba23e66a8c79168ba6c414c742a32',
      role: 'ARTIST',
      email: 'mromoda7@gmail.com',
      displayName: 'romoda',
      fullName: 'Mario Romoda',
      imageUrl:
        'https://storage.googleapis.com/endemic/profile/1689710569887-autoportret_1.jpg',
      description:
        'Mario Romoda was born 15.04.1987 in Vukovar . He grew up on the island Krk where he attended elementary school . School of Applied Arts, Textile and Design writes and ends in Osijek . In Zagreb in 2006 he decide direction in painting at the Academy of Fine Arts . He graduated in the class of Zoltan Novak 2012.\nAfter his schooling, his work is embedded in various experimental solutions that lead to a problem of survival issues such as life polemics and painting itself. So far he has had 13 solo exhibitions and many recognized collections. He has been rewarded and recognized many times by critics and audiences.\n\nHe lives and works in Zagreb.',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@romoda',
    },
    {
      id: '0x3d987415c9e9f682b082ffe2e11a11f1eab91db5',
      role: 'ARTIST',
      email: 'Domagojbaricatelje@gmail.com',
      displayName: 'barich',
      fullName: 'Domagoj Barich',
      imageUrl: null,
      description:
        'Domagoj Barich was born on June 19, 1988. in Rijeka, where he graduated from the School of Applied Arts. He continues his education at the Academy of Fine Arts in Zagreb, majoring in painting. He graduated in 2012, in the class of Prof. Zoltan Novak, with which he obtained the title of master of painting. 2014-2016 at the Academy of Fine Arts in Rijeka. worked as an external associate. He participated in the painting of the Shree Peetha Nilay ashram in Germany. He made the altarpiece in the ISKCON temple in Rijeka, and the altarpiece in the Bakti Marga temple in Škrljevo. Participates in the painting of the Stations of the Cross in the church on Lošinj. He is the co-organizer of the 1st Biennale Opatija in 2023. He is a member of HDLU Rijeka and over the years has participated in a number of collective and independent exhibitions.',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@barich',
    },
    {
      id: '0x9ae1cae1dda1b38365764220aa94cca4da83708f',
      role: 'ARTIST',
      email: 'alma.trtovac.zg@gmail.com',
      displayName: 'almadillothefirst',
      fullName: 'Alma Trtovac',
      imageUrl:
        'https://storage.googleapis.com/endemic/profile/1687007844784-Screenshot_2023-05-25_at_15_15_57.png',
      description:
        'The works that I create are oriented towards breaking the viewers’ illusion about reality as a linear/ homogeneous/ mutual phenomenon and offering them an experience of perceiving reality  as something heterogeneous/ fragmented and ultimately non-existent (as a form of simulation in which anything is perceived as equally  real).\n\n The motives that the works depict (usually elements of urban environments which are visually conflicted and symbolize various social, political and inner dichotomies) question the layers of reality in a metaphysical and symbolical aspect, and can be referenced with the technical process of creating a painter’s composition. By combining documentary realism of photography and video, I create a so called archive of (mental) images, which I later on deconstruct and turn into a collage together with fragments of memories about the same location/situation to, ultimately, synthesize it into a single mental landscape.\n\n',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@almadillothefirst',
    },
    {
      id: '0xa0f0c9da19372f0fdd7e34ca8d61b191dde9d467',
      role: 'ARTIST',
      email: null,
      displayName: 'kresimirbuden',
      fullName: 'Krešimir Buden',
      imageUrl:
        'https://storage.googleapis.com/endemic/profile/1692013498480-2Fast_foto_za_najavu.jpg',
      description:
        'Born in Zagreb, capital of Croatia. After finishing the School of\nApplied Art and Design, start to work as a graphic designer and\nillustrator. 1995th became a member of Croatian Association of\nApplied Arts and participates in numerous exhibitions at home\nand abroad. 1998th he became a member of the Croatian Society\nof Independent Artists ( HZSU ).\nSince 1988, engaged in graffiti writing (nick name 2Fast),\none of the founders of the Croatian graffiti scene. Take part\non many domestic and international exhibitions and jams.\nConstantly looking for new shapes, moves and techniques,\nexploring media and materials. Last years combine street\ngraffiti into three-dimensional objects, grounded in street\nart through use of its characteristic iconography (arrows,\nnumbers and letters) physically depart the two-dimensional\nsurface by penetrating into space and are seen suspended in\nthe motion of curvature and rotation, forming unusual and\ninnovative dimension of graffiti art.\n‘2Fast belongs to the small group of graffiti-art population who did\nnot channel its youthful frustrations and potential into quick and\nfrivolous vandalisation of the public property, but rather finished\nthe School of Applied Art and Design and started working as a\ndesigner at the age of 18. In that sense, he ended up on the ‘other\nside of the fence’ and adopted the way of thinking of academically\neducated artists, such as Keith Haring or Jean-Marie Basquiat,\nknown for finding inspiration in the raw creative energy of graffiti art\namateurs and adopting the aesthetic forms and stylistic\nelements of the genre’, stated dr. sc. Darko Bekić in his foreword to\nhis latest solo exhibition exhibition.',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@kresimirbuden',
    },
    {
      id: '0xaf223c4f0895c1a6f389aa3ca5c28b0f6c5f76fa',
      role: 'ARTIST',
      email: null,
      displayName: 'lonac',
      fullName: 'Lonac',
      imageUrl:
        'https://storage.googleapis.com/endemic/profile/1692176312440-lonac.jpg',
      description:
        'Tomislav Lončarić (1987, Zagreb). He completed primary school in Zagreb. After graduating from the Zagreb School of Art in 2006, he enrolled at the Academy of Fine Arts in Zagreb, specializing in Teaching. He graduated in 2013 in the class of Prof. Ines Krasić. Since 2013, he has been a member of the P_3 platform, and since 2016, a member of the Croatian Association of Artists (HDLU). He has exhibited in six solo exhibitions and numerous group exhibitions, both locally and nationally, as well as internationally. Some of his studio works are part of private and public collections, with one of the more significant collections being artworks acquired and displayed at the European Central Bank (ECB) in Frankfurt, where he exhibited in a group exhibition of Croatian contemporary artists in 2019. The founder of Street Art Belgium and organizer of numerous international street art festivals included Lonac among the 50 most influential street art artists in his book, "Street Art Today: The 50 Most Influential Street Artists Today." Tomislav Lončarić, better known by his artistic name Lonac, has, over the past decade, placed Croatia on the world map of muralism and street art culture with his creative work. His murals adorn the streets of cities around the world (Croatia, UK, Italy, France, Bosnia and Herzegovina, Kosovo, Switzerland, Sweden, Belgium, Denmark, Portugal, United Arab Emirates, China, South Korea, North Macedonia, USA).',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@lonac',
    },
    {
      id: '0x6fead5d35f1778eea7c640016635aad53d0475e6',
      role: 'ARTIST',
      email: 'davor.dmitrovic@hotmail.com',
      displayName: 'davor_dmitrovic',
      fullName: 'Davor Dmitrović',
      imageUrl: null,
      description:
        'Artist from Zagreb, Croatia (1989), got his MA in Printmaking. Currently on PhD Painting and Printmaking at China Art Academy. Exhibited solo and in a bunch of group shows in Croatia and abroad.',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@davor_dmitrovic',
    },
    {
      id: '0xff9567efeda4880d054f91674ddda5b8345e350c',
      role: 'ARTIST',
      email: 'juricapusenjak1@gmail.com',
      displayName: 'jerry_j',
      fullName: 'Jurica Pusenjak',
      imageUrl:
        'https://storage.googleapis.com/endemic/profile/1691234709658-Dollar.jpeg',
      description: '',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl:
        'https://storage.googleapis.com/endemic/profile/1691234751166-ZF002954-dark.jpg',
      slug: '@jerry_j',
    },
    {
      id: '0xd60264891addfcd3116049b94a74a6d2b419c29f',
      role: 'ARTIST',
      email: null,
      displayName: 'unnamed231',
      fullName: 'unnamed',
      imageUrl: null,
      description: null,
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@unnamed231',
    },
    {
      id: '0x12a2b954bcd7dedc35af27942de2b418366440ac',
      role: 'ARTIST',
      email: 'vida.loca.mgmt@gmail.com',
      displayName: 'vida_loca_mgmt',
      fullName: 'Vida Janeković',
      imageUrl: null,
      description: '',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@vida_loca_mgmt',
    },
    {
      id: '0x3ef6e541349a6f117a74671204fade8c3ed55f19',
      role: 'ARTIST',
      email: 'melindasefcic@gmail.com',
      displayName: 'melinda',
      fullName: 'Melinda Šefčić',
      imageUrl:
        'https://storage.googleapis.com/endemic/profile/1691153743164-Melinda-S_efc_ic__allabaoutchange-9.jpg',
      description:
        'In 2018 Melinda Šefčić received her Ph.D. in the field of art and science entitled Re-humanisation and re-aesthetization in the hospital: An example of artistic treatment of one hospital department, under the mentorship of Prof. Svjetlan Junaković and Prof. Vera Turković, Ph.D. \nShe has showcased her work at numerous solo and group exhibitions in Croatia and around the world. She is the author of over 20 art projects, and over 50 murals, and has participated at numerous congresses and conferences. She is a member of the Croatian Association of Fine Arts (HDLU) and the Croatian Society of Freelance Artists (HZSU) and director of the Art Organization MURAL HUB.\n',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@melinda',
    },
    {
      id: '0x0611853d7535f03f5b7ec71b1f39f4f06fc3c9ef',
      role: 'ARTIST',
      email: null,
      displayName: 'sandaanderlon',
      fullName: 'Sanda Anderlon',
      imageUrl: 'https://storage.googleapis.com/endemic/profile/sanda.jpeg',
      description:
        'After getting a BA degree from Zagreb School of Design, Sanda made a turn towards art and self-initiated works - mainly in the medium of digital collage. It resulted in Lumas gallery chain representation with headquarters in Berlin and best-selling editions. Her collage works were exhibited during Art Basel and commissioned by BBC, Financial Times, Lenovo and Canal+ among others.',
      isVerified: true,
      isFeatured: true,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@sandaanderlon',
    },
    {
      id: '0xa064cafe49fae64c24132b438c31cdbf1c4c5eae',
      role: 'ARTIST',
      email: null,
      displayName: 'rodrigo',
      fullName: 'Rodrigo Vargas',
      imageUrl:
        'https://storage.googleapis.com/endemic/profile/1691508422729-Screenshot_from_2023-08-08_17-26-52.png',
      description:
        'Rodrigo Vargas is a multidisciplinary artist and freelance curator based in London\nand Barcelona. He has a bachelor’s degree in Mixed Media Fine Art from Central\nSaint Martins and has exhibited in a variety of online and offline spaces, such as\nAmbika P3, Tate Modern (Exchanges Program), 508 Kings Road Gallery, and Tecla\nSala.\n“My practice is a response to the artistic shock moving from Bogotá to London\nproduced in me. During my early years, I was exposed to the beauty and\ntimelessness of the visual arts, within offline spaces. I was a museum child, and I\nexperimented throughout my teens with painting and sculptural mediums. I believed\nit to be the epitome of creativity.\nOnce I moved to London, I realized the capabilities of the digital medium for creative\nexpression. I started experimenting with various software to create compositions to\nbe enjoyed as artwork exclusively in the digital sphere. Since then, I’ve been creating\nart under different pseudonyms and avatars, in the hopes of detaching my physical\nbeing from my digital presence, and to challenge the notion of the “celebrity artist”. I\nconsider my art to fall under the canon of contemporary art, with specific\ncategorizations of digital art, and net art.\nIn conjunction to this, I’ve curated a series of hybrid shows exploring the\ninterrelations of the digital medium and the commercial physical art world. In this I’ve\nhad the opportunity to collaborate with various NFT platforms as a curator and\nconsultant.\nI hope my series offers a short view into the creative capacities of a visual artist with\ndigital tools. Thank you for offering me a platform to showcase my work”.',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@rodrigo',
    },
    {
      id: '0x150804e319fbeca38b68ed7d1b045c79aeab8199',
      role: 'ARTIST',
      email: 'sonja@enemic.app',
      displayName: 'sonjapavlina',
      fullName: 'Sonja Pavlina',
      imageUrl:
        'https://storage.googleapis.com/endemic/profile/1691503562278-Profilna_sonja.jpg',
      description:
        "Sonja Pavlina was born 07. 02. 1989. in Zagreb. In year 2007. She graduated from the School of Applied Arts and Design in Zagreb. 2012. She graduated painting in Academy of Fine Arts in doc. Zoltan Novak's class, and got title, Master of painting. She was recognised as the most succesful grauate by the ALU professor's council two years in a row, and she won a Rectors Prize in 2012.\nShe exhibited in several group, and had many solo exhibitions in Croatia and foreign countries. She lives and work in Zagreb, Croatia.",
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@sonjapavlina',
    },
    {
      id: '0xb5058324955e65230df4e37d947c1a60794483a5',
      role: 'ARTIST',
      email: 'radzinskimark@gmail.com',
      displayName: 'aantongroshikov',
      fullName: 'Anton Groshikov',
      imageUrl:
        'https://storage.googleapis.com/endemic/profile/1690553020087-IMG_9848.jpeg',
      description: 'digital artist from nowhere',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl:
        'https://storage.googleapis.com/endemic/profile/1690553021926-IMG_0796.jpeg',
      slug: '@aantongroshikov',
    },
    {
      id: '0x56459a670bea3b8a5050273a25d6941c6fcea143',
      role: 'ARTIST',
      email: null,
      displayName: 'unnamed029',
      fullName: 'unnamed',
      imageUrl: null,
      description: null,
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@unnamed029',
    },
    {
      id: '0x596fd9beb32dc2745994cfa50f541979cf85e886',
      role: 'ARTIST',
      email: 'alexauer.sound@gmail.com',
      displayName: 'prpl_tenshi',
      fullName: 'Aleksandra-Mariya Bauer',
      imageUrl: null,
      description: 'The Artist, Illustrator',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@prpl_tenshi',
    },
    {
      id: '0xfb3245a7af6d2c9a6577949898d780a091712b88',
      role: 'ARTIST',
      email: null,
      displayName: 'unnamed439',
      fullName: 'unnamed',
      imageUrl: null,
      description: null,
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@unnamed439',
    },
    {
      id: '0xfd7d71272e991396c70183938ea5fc9db4f439df',
      role: 'ARTIST',
      email: 'iva.habus7887@gmail.com',
      displayName: 'ivakarla7',
      fullName: 'Iva Karla Habus',
      imageUrl:
        'https://storage.googleapis.com/endemic/profile/1691183606307-1682454943140.jpg',
      description: 'Academy of Fine Arts 2017.',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl:
        'https://storage.googleapis.com/endemic/profile/1691183611015-1682454943158.jpg',
      slug: '@ivakarla7',
    },
    {
      id: '0x2b788565fd68f4a9fa37bed676ca2c174e7bc1cb',
      role: 'ARTIST',
      email: 'luka.martinis@gmail.com',
      displayName: 'lukam',
      fullName: 'Luka Martinis',
      imageUrl: null,
      description: '',
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl:
        'https://storage.googleapis.com/endemic/profile/1690803000772-20230727_133349.jpg',
      slug: '@lukam',
    },
    {
      id: '0x9fe41940663515e3c31d6224083530b0d88d51f0',
      role: 'ARTIST',
      email: 'petragrozaj@gmail.com',
      displayName: 'petragrozaj',
      fullName: 'Petra Grozaj',
      imageUrl:
        'https://storage.googleapis.com/endemic/profile/1691484318651-petra-profil.jpeg',
      description:
        "Petra Grozaj graduated from Academy of Fine Arts and from School of Apllied Arts and Design in Zagreb. She has won a Rector Price of Zagabria University, Academy of Fine Arts award and receved grands. She exhibited at many solo and group shows and participated in art project in Croatia and abroad. She was presenting Croatia at Biennial of Young Artists BJCEM in Naples, and was at art Residences Cite Internationale des Arts in Paris, GlogauAIR in Berlin and One Sided-Story Spinnerei in Leipzig. 2017. is exhibiting at Museum of Contemporary arts Zagreb. Her paintings are part of galleries and private collections. \n\neducation\n\n2002  MA / Academy of Fine Arts  Zagreb\n\n1995- 2000  Academy of  Fine Arts  Zagreb\n\n1993  graduated  at  School of Arts and Design  Zagreb\n\nresidences, projects / selection\n\n\n2023 Art Residency ''Holon.Art'', Wels, Austria \n\n2020 Art Residency ''De/konstruction of painting '' Hafenkombinat Leipzig, \n\n              Organized by HDLU Zagreb\n\n2019 / 2020  Leading /teaching painting group program at HDLU Project ''START 54+\n\ncurating student exhibition at HDLU Gallery Prsten, writting and promoting\n \nCataloque at HDLU Gallery Prsten\n\nProject Financied by Europe Union and Croatian Ministry of Culture \n\n2019 FECIT International painting simposium Grožnjan, organized by Publishing \n\n           House Klett\n\n2016/17 Studio Spinnerei Leipzig / working on show Scholia Painters dialogue\n\n             for Museum of Contemporary Art in Zagreb\n\n2017  IFA - Institut fur Auslandsbeziehungen for the Exhibition and project with\n \nLeipzig painter Maria Sainz Rueda projekt Transition in Progress/ Painters Dialogue\n\n2015 /17 Transition in progress/ in collaboration with Goethe- Institut Croatia\n\n2012/13  Art Residence  One Sided story, Spinnerei Leipzig\n\n2008  Art Residence  program Glogau AIR  Berlin\n\n2007  Art Residence  Cite Internationale des Arts  Paris\n\n2005  Int. Painting Symposium, Museum of Contemporary Art, Casoria/ Napoly\n\n           at  BJCEM  Biennal of Young artist of Europe and Mediterranean\n\n           Castel Sant'elmo, Napoly Italy \n\n2005  Painting and Sculpture workshop, Croatian artists, Academy of Fine \n\n          Arts Kiev Ukraina and Academy of Fine arts Moscow Russia, Island of Brač\n\n2000  Art education courses, Academy of FA Zagreb and Northen Illinois University\n\n          USA, Island of Hvar\n\n2000  International Illustration course, Teatrio Associazione Culturale ,Venice  Italy\n\nsolo exhibitions / selection\n\n\n2022 Shining/ Gallery Kljaković, Zagreb\n\n2021 Kaleidoscope/Contemporary Gallery Lauba/House for Art and people,Zagreb\n\n2019 Krystal / Gallery Galženica, Velika Gorica, Croatia\n\n2019 The wall / Pogon Jedinstvo/ Gallery 90-60-90, Zagreb\n\n2019 Moonlight / Gallery Decumanus Town and Island of Krk, Croatia\n\n2017  Scolia Painters dialogue / Museum of Contemporary Art Zagreb\n\n           with Maria Sainz Rueda \n             \n2017 Between line and painting/ Gallery Zuccato Poreč \n\n          with Stipan Tadić and Ivona Jurić\n\n2016  Out of the blue, Gallery Događanja, Zagreb \n\n2015  Transsition in progress/ A dialog, with Maria Sainz Rueda, Westpol, Leipzig\n\n2013  Moments in time, Gallery Barrel HDLU  Zagreb \n\n2012  Mystic magic sweet, Gallery Knežev dvor, Rab \n\n2011  Moments in time, Gallery Zilik, Karlovac \n\n2010  Paintings by observing, gallery Buljat, Zagreb \n\n2008  Everything is the same story,  Matica Gallery, Zagreb \n\n2008  Canceled, Prostor Zagreb \n\n2008  On the other side, Gallery Marisall  Zagreb \n\n2006  Ladies from catalogue, Modern Gallery ,Studio Racic Zagreb \n\n2005  1:1 ,Gallery Artbug,Bassano del Grappa Italy \n\n2005  Recycles, Start solo Gallery Nova Zagreb \n\n2004  Me, myself & I, Gallery B.Bernardi Zagreb \n\n2004  Appearing and dissapearing, Gallery Karas Zagreb \n\n2003  1 : 1 , Gallery Kordic,Velika Gorica with Ivan Fijolić \n\n2003  1 : 1, Galery Vladimir Nazor Zagreb \n\n2001  New ,Gallery V.Nazor Zagreb \n\n1999  Days of Europa movies ,Kinoteka Zagreb \n\n1999  Paintings, first solo show, Gallery SC Zagreb \n\ngroup exhibitions / selection\n\n\n\n2022 Art & Grad/ Gallery Lauba, Zagreb\n\n2022 Triennal of Croatian sculpure/ HDLU Gallery Ring, Zagreb\n\n2022 Nesvrstani Art fair/ Platform for contemporary art, Gallery 90-60-90/ Lauba, \n\nZagreb\n\n2022 Start collection< 300/ Holon Gallery, Wels Austria\n\n2021 6th Biennal of Painting/ HDLU Zagreb\n\n2021 Portrait, Holon Gallery, Wels Austria\n\n2021 Light visions/ Lions Croatia, Gallery Klovićevi dvori, Zagreb\n\n2021 Art & Grad/ Gallery Lauba, Zagreb\n\n2021 Nesvrstani Art fair / with Gallery ''S'' Špoljar Koprivnica, Lauba, Zageb\n\n2020 Art Zagreb / Tehnical Museum Nikola Tesla, Zagreb\n\n2020 Nesvrstani art fair  / Platform for contemporary art, Gallery 90-60-90/ Lauba,\n\nZagreb\n\n2019 De / Construction of painting / Gallery Karas, Zagreb\n\n2019 Known unknowns / Gallery Westpol A.I.R. / Leipzig, Germany\n\n2019 Exhibition of international art simposium / Fecit / Lauba, Zagreb\n\n2019 Fecit / Gallery DLUL/ Ljubljana, Slovenia\n\n2018 Loneley as rinosaurus/ Gallery ULUS, Beograd Serbia\n\n2018 Fecit / Town Gallery FONTICUS / Grožnjan Croatia\n\n2015  3rd Croatian Biennal of Painting, HDLU, Zagreb\n\n2013  Wasser Schopfen / Zagrabiti, Gallery Barell, Gallery Ring and Gallery PM,\n\n           HDLU, Zagreb Lepzig / Zagreb group show\n\n2013  Mutatis Mutandis, One Sided Story, halle 14, Spinnerei Leipzig\n\n2011  Millenium Development goals, World bank Gallery, Zagreb\n\n2010  30th Youth Sallon, Gallery HDLU/ Marisall, Zagreb\n\n2010  Recent exhibition, Gallery HDLU, Zagreb \n\n2009   Souvenir , Kunstraum Kreuzberg / Bethanien, Berlin\n\n2008   Open studios , Glogau AIR  Berlin\n\n2008   AAP exhibition , Hofgalerie Graz, Austria\n\n2007   5 + , Gliptoteka of Croatian Academy of Science and Art  Zagreb\n\n           Exhibition of Students who got Rector University Award \n\n2006   Format, Kunstlerhaus, Graz Austria\n\n2006   New Fragments, Museum Mimara, Zagreb\n\n2006   39. Zagabrian salon, 'Art is medium' HDLU Zagreb\n\n2006   White night, Museum of Skopje town, Skopje Macedonia\n\n2005   BJCEM  Biennal of Young artist of Europe and Mediterranean\n\n            Castel Sant'elmo, Napoly Italy\n\n2005   Iperpitura, Gallery Isola Bassa, Dolo, Padova Italy\n\n2005   Passion, Museum of Modern and Contemporary art Rijeka \n\n2005   International Painting simposium, Museum of Contemporary art Casoria/\n\n            Napoly Italy\n\n2004   27 th Youth Sallon, HDLU Zagreb\n\n2004   3 rd Croatian Triennal of graphic , HDLU Zagreb\n\n\n2003   New fragments ,Gliptoteka of Croatian Academy of Science and Art Zagreb\n\n2003   3rd Triennal of drawings,  Gallery Klovićevi dvori Zagreb\n\n2002   New fragments, organised by Erste&Steierm. Bank,Gallery SC Zagreb\n\n            Gallery GAL Rijeka\n\n2002   Rector winers prize ,Gallery VN Zagreb\n\n2001   90-60-90, Aqarius art Zagreb\n \n           Blue bird, Zagreb\n\n2000   7 th Triennal of Sculpture, Gliptoteka of Croatian Academy of Science and Art \n \n2000   2 nd Triennal of Graphic , Art pavilion Zagreb\n\n1999  Days of Europa movies ,Kinoteka Zagreb / S\n\n1999  Paintings, Gallery SC Zagreb / S\n\n1999  One mounth at the country, Art Club Attack Zagreb\n\n1999   University review exhibition, Gallery SC Zagreb\n\n1999   Pasion Legacy, Gallery Klovičevi dvori, Zagreb\n\n1998   Art Academy Zagreb exhibition, Museum of Vukovar town, Vukovar\n\n1998   25 th Youth Salon,  HDLU Zagreb\n\nAwards\n\nAcademy of Fine Arts Zagreb Award for the best show, Rector Award Of Zagabria\n\nUniversity, Grant of Zagreb town for One Sided Story residence in Leipzig, Grant of\n \nCroatian Ministry of Culture for Art Residence Cite International des Arts Paris,\n \nGrant of 'Hrvatska kuća- Croatia house' for project Transsition in Progress/ A dialog\n\nGalerry Westpol in Leipzig, Grand of IFA- Institut fur Auslandsbeziehungen for the\n \nExhibition and project with Leipzig painter Maria Sainz Rueda projekt Transition in\n\nProgress/ Painters Dialogue\n\n\n\nprofesional membership\n\n2000  Croatian Assotiation of Artist,\n\n2005  Croatian Freelance Artist Assotiation\n\n\n\nbibliography | selection\n\n2021 Romina Peritz/ Jutarnji list/ Petra Grozaj texts about exhibition \n\nKaleidoscope in Lauba Zagreb\n\n2021 Maja Car/ Večernji list/ 12th april, article for solo show Kaleidoscope in Lauba\n\n2021 Lana Harjaček/ cards for solo show Kaleidoscope/ Gallery Lauba Zagreb\n\n2020 Tia Špero/ Večernji list/ article about Art fair Nesvrstani lauba Zagreb\n\n2020 Daniel Tomičić/ Art zagreb/ preface for Art fair\n\n2020 Miran Jurić, Nika Šimičić/ Start 54+, preface for catalogue\n\n2019- 2020 Zagreb in your pocket cover '' Getting ready''/ Cool-ture winter\n\n2019 Ivana Mance, Marijana Stanić/ ''Zid'' Gallery 90-60-90,Pogon Jedinstvo, \n\nPlatform for Contemporary art Zagreb\n\n2019 Tena Bakšaj, Josip Zanki/ De/ construction of painting/ Gallery Karas/ HDLU\n \npreface for catalogue\n\n2019 Patricija Kiš / Jutarnji list/ article about show in Gallery Galženica\n\n2019 Klaudio Štefančić/ Gallery Galženica/ Krystal, foreword and interview\n \nfor cataloue of exhibition\n\n2019 Falk Messerschmidt / Known unknowns/  Gallery Westpol Leipzig\n\n2019 Višnja Slavica Gabout / Link in arts/ Moonlight/ Foreword for catalogue /Gallery\n\nDecumanus Islland of Krk\n\n2018  Eugen Borovsky,Loneley as rinosaurus /Fecit Grožnjan/ proloque at catalogue\n\n          International artist summit\n\n2017 Patricija kiš/ Petrada/ Jutarnji list/ Article about exhibition at Museum of \n\ncontemporary art Zagreb, Scholia/ Painters dialogue\n\n2017 Patricija Kiš / Jutarnji list/ Zuccato, Faces as masks, landscapes and crushed \n \n         Animals\n\n2017 Patricia Počanić/ Between line and painting/ Foreword for catalogue / Gallery \n\nZucatto Poreč, show with Stjepan Tadić and Ivona Jurić\n\n2017  Leila Topić, Scholia/ Commentary of the works, \n\n          Transition in Progress and Scholia Paintings in dialogue Westpol Leipzig\n\n          and  Museum of Contemporary Art Zagreb\n\n2016  Jospa Bubaš, Out of the Blue, galerija Događanja, Zagreb\n\n2015  Željko Marciuš, 3. Bijenale slikarstva, 3rd Bienal of painting, Slika-slikarstvo\n\n           -  ne(slikarsvo)\n\n2015  Patricija Kiš, Biennal of painting, 38 umjetnika koji čine aktualnu hrvatsku\n\n           slikarsku scenu, Jutarnji list\n\n2015  Maja Hrgović, Uz 3. Bijenale slikarstva, veliku izložbu u Domu HDLU,\n \n           Dobri stari Kist i štafelaj, Novi list, str 24\n\n2015  Iva Kobler, Likovno povečalo, Treći bienale slikarstva- bahato\n           'zagrebocentričan' pregled hrvatske umjetnosti, Nacional,br. 914\n\n2015  Tea Akrap, Suvremena Slikarska scena u Meštorvićevom paviljonu\n\n           Cro life, str. 8, A3\n\n3013  Iva Kobler, Petra Grozaj, Momenti u vremenu/ Moments in timeZagreb, HDLU/\n\n          Croatian Assosiation of Artists\n\n2012-2013  Candace Goodrich, Jonathan Beer, lasse Antonsen, One sided story\n\n          / artist residency,Leipzig, published by OSS leipzig\n\n2012  Nataša Ivančević, Slikarsvo petre Grozaj, 'Mystic magic sweet' \n\n          Galerija Knežev dvor, Rab\n\n2011  Nikola Albaneže, 'The guardia of changes' for 'Moments in time' Gallery Zilik, \n\n           Karlovac\n\n2010  Iva Kobler, Paintings by observing, Gallery Buljat, Zagreb\n\n2010  Nikola Albaneže, Creative and other production, The exhibion of recenzt \n\n           Works of croatian association of artist members, Gallery HDLU, Zagreb\n\n2008   Ivana Mance, At the other side, Marrisal Gallery , Zagreb\n\n2006  Patricija Kiš, Painter and models from the changing room, Jutarnji list, \n\n           Kultura, Zagreb\n\n2006  Željko Marcius Young ladies from catalogue, Modern gallery, \n\n          Studio Josip Racic, Zagreb\n\n2006  Flavia Fricano and Chiara Zago, Iperpitura,Gallery Isola Bassa, Dolo, Italy\n\n2005  Branko Franceschi, Passion, Biennial of Young artists of Europe and\n\n           Mediterranean,Croatia, Visual arts, Castel Sant Elmo, Naples, Italy\n\n2005  XII edition of Biennial for Young artists of Europe and Mediterranean, \n\n          Castel Sant Elmo, Naples, Italy\n\n2005  Mladen Lučić, Iva Kobler, 39. Zagreb Sallon, Art is media,\n \n          Croatian Assotiation of Artists, Zagreb\n\n2004  Enes Quien, Arising and Vanishing, Gallery Karas, Zagreb\n\n2004  Vlasta Tolić, Recycling as an artistic method, Vjesnik, Kultura, Zagreb\n\n2004  27. Youth Sallon, Diversity as dominant feature, Forward/ prize awarding \n\n           Comittee of 27 youth salon, Croatian Association of the artists, Zagreb\n\n2003  3 th Triennial of Graphics,Accademy of Arts and Sciences,Zagreb\n\n2002  Nikola Albaneze 3th Triennail of Drawings, Graphics institute, Zagreb\n\n2000  Ivica Župan, 7th Triennail of Sculpture, Glyptotheke Zagreb\n\n1999  Tatjana Smojver, Autoportraits of Petra Grozaj, Me, myself & I solo show,\n \n          Galery CEKAO, Open University Zagreb\n\n1998  Klaudio Stefancic, 25th Youth Sallon, Croatian Association of Visual Artists, \n\n           Zagreb\n",
      isVerified: true,
      isFeatured: false,
      isSuperstar: false,
      isCollector: false,
      headerImageUrl: '',
      slug: '@petragrozaj',
    },
  ];

  const EndemicCollectionFactory = await ethers.getContractFactory(
    'EndemicCollectionFactory'
  );
  const endemicCollectionFactory = await EndemicCollectionFactory.attach(
    endemicErc721Factory
  );

  const MINTER_ROLE = await endemicCollectionFactory.MINTER_ROLE();

  for (let i = 0; i < verifiedUsers.length; i++) {
    const tx = await endemicCollectionFactory.grantRole(
      MINTER_ROLE,
      verifiedUsers[i].id
    );

    await tx.wait();

    console.log('Granted role for:', verifiedUsers[i].id);
  }
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
